openapi: 3.0.0
info:
  title: MyGymBro API
  description: API for managing user registration, routines, and training plans.
  version: 1.0.0

paths:
  /api/users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                dni:
                  type: string
                role:
                  type: string
                  enum: [admin, trainer, user]
      responses:
        '201':
          description: User registered successfully.

  /api/routines:
    post:
      summary: Create a new routine
    get:
      summary: Get all routines

  /api/training-plans:
    post:
      summary: Create a new training plan
    get:
      summary: Get all training plans
