name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # Paso 3: Instalar Poetry
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -

    # Paso 4: Configurar Poetry en el PATH
    - name: Add Poetry to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    # Paso 5: Instalar dependencias
    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    # Paso 6: Ejecutar los tests
    - name: Run tests with pytest
      run: poetry run pytest --cov=./ --cov-report=term
